name: Build static site and inject Azure key

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create secret file
      run: |
        echo "export const SECRET_KEY = '${{ secrets.AZURE_AI_KEY }}';" > secret.js

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: |
          ./
          !.git/
